#!/usr/bin/env rake

#require 'rake/clean'
#CLOBBER.include("foodcritic")
#task "cheftest" => ["init", "compile"]

BASE_DIR = File.dirname(__FILE__)
TARGET_COOKBOOKS_NAME = [ "rbenv", "test_recipe" ]
TARGET_COOKBOOKS_PATH = "#{File.dirname(__FILE__)}/{#{TARGET_COOKBOOKS_NAME.join(',')}}"

desc "chefspec to target cookbooks"
task :rspec do |t|
  puts "-- #{t.name} running -- "
  if Gem::Version.new("1.9.2") <= Gem::Version.new(RUBY_VERSION.dup)
    require 'rspec/core/rake_task'
    RSpec::Core::RakeTask.new(:rspec) do |t|
      spec_files_path = "#{TARGET_COOKBOOKS_PATH}/spec/*_spec.rb"
      t.pattern = spec_files_path
      t.rspec_opts = ['-c']
    end
  end
end


desc "Runs foodcritic linter"
task :foodcritic do |t|
  puts "-- #{t.name} running -- "
  if Gem::Version.new("1.9.2") <= Gem::Version.new(RUBY_VERSION.dup)

    TARGET_COOKBOOKS_NAME.each do |cookbook|
      file_path = File.join(BASE_DIR, cookbook)
      sh "foodcritic --epic-fail any #{file_path}"
    end

  else
    puts "WARN: foodcritic run is skipped as Ruby #{RUBY_VERSION} is < 1.9.2."
  end
end


desc "detect awful code"
task :flay do |t|
  puts "-- #{t.name} running -- "
  require "rake/tasklib"
  require "flay"
  require "flay_task"
  puts BASE_DIR
  threshold = 25
  flay = Flay.new({:fuzzy => false, :verbose => false, :mass => threshold})
  flay.process(*Flay.expand_dirs_to_files([BASE_DIR]))

  flay.report
end

task :default => [:rspec, :foodcritic, :flay]
