#!/usr/bin/env rake

require 'rake/clean'
CLOBBER.include("foodcritic")

task :default => 'foodcritic'

#task "cheftest" => ["init", "compile"]

desc "Runs foodcritic linter"
task :foodcritic do |t|
  puts "-- foodcritic #{t.name} running -- "
  if Gem::Version.new("1.9.2") <= Gem::Version.new(RUBY_VERSION.dup)
    #sandbox = File.join(File.dirname(__FILE__), %w{tmp foodcritic cookbook})
    #prepare_foodcritic_sandbox(sandbox)

    sh "foodcritic  /home/masuda_kenichi/repos/masudaK-chef/cookbooks/rbenv"
  else
    puts "WARN: foodcritic run is skipped as Ruby #{RUBY_VERSION} is < 1.9.2."
  end
end

def prepare_foodcritic_sandbox(sandbox)
  files = %w{*.md *.rb attributes definitions files libraries providers
recipes resources templates}

  rm_rf sandbox
  mkdir_p sandbox
  cp_r Dir.glob("{#{files.join(',')}}"), sandbox
  puts "\n\n"
end

